(package "ChatGPT.el"
         "0.1.0"
         "API for interacting with ChatGPT")

(website-url "https://github.com/jcs090218/chatgpt")
(keywords "comm" "gpt")

(package-file "ChatGPT.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "request")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
